name: Deploy Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy VM using ARM/Bicep/Terraform (sample = Azure CLI)
      - name: Create Resource Group
        run: az group create -n github-demo-rg -l eastus

      - name: Create VM
        run: |
          az vm create \
            --resource-group github-demo-rg \
            --name github-demo-vm \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --generate-ssh-keys
